version: 2
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.10
  tools:
    python: "3.11"  # Keep in sync with .github/workflows/tests.yml

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
