language: python
branches:
  only:
  - master
  - /^\d\.\d+$/
  - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.7
    env: TOXENV=mypy
  - python: 3.7
    env: TOXENV=docs
install:
- pip install -U tox codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: MunaE0D2sEkNOrtBcp5adZueImdXmn9Wobd6XnKwaEhA/v6aNDwXAUjUvgrFLpidQm4OI0wORPiArnOht2sGxKltILOVXK630vtwNna3FpJCZd4EGa/KGCR6AMtJW6UlopzyXkIXzEHta0HbPRgFKVTjeeRMh+SygP0Vba0eKIF2AgzAitl4GCRj9oOhNfZQjktCFV1euG49TLoqWdYpedxBu8KpJGC/6wk2Q1DiPTclE28xNZ1imjBtVuUIqsoRlLxMBhxCkAyuCs2a5C9mm8AsCXE5RnZc/8KakdI32Cqgk5XnZjFAmCDfrwDqNHoiBb+aT1kuY+P62E99kU1GxchqSQ+COLktBbsJrpBXQx2UBQ0yuu/ZozFR82nRxiDtvwzhRqVE4LbTihekEMy+OBIk+JcD3FtWYX4oFyuW1rMlo7CvIaFEHOsUpov60KrJMQ44LrASW2Fp6InQL8Jjwr6nceeIVgpB2CQsuUCJxwKSjY9b13fsEM27OcxhTrj6o7X2yIhnR6fPlmtYjFvXe5OtM8Op/CzpUim+/TG7Bi0gP9RvS3FvHeGwbnebyQw7jZhD/QU7WVThuHjyhTOkTJLN1SteMv4bFBKNrdW70COotArP2NdWFIwWb9SVoRuMUNtvb91mIyOGoZ0Ojh8QGcQRGQjkJoAlrAgQhdaatjM=
  on:
    tags: true
    repo: scrapinghub/scrapy-poet
    condition: "$TOXENV == py38"
  distributions: sdist bdist_wheel
