language: python

branches:
  only:
  - master

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.7
    env: TOXENV=mypy

install:
- pip install -U tox codecov

script: tox

after_success:
- codecov

deploy:
  provider: pypi
  user: kmike
  password:
    secure: cdEikDuOBG/ZIOeNhvzt/KNPJsgV7RMO6k2yRVFdz/UZmdVrdrPXrR+1a7ui302POCiRaFe1vh4ukyqQN5KBsOOlMMfnN4By7dernvne8DPYxM/UDlCOLtVJz0TOzCWDcJBiz/dHcXh49HFOj6StVSAc8dHGIP7RYIs0Hfqly7UyOF0bnJXpd8YGyURjY2gwJD0DAc5/GKbWF+xJeNtGKxB0BysB5x/2+icJTlfF3Y0WPzzaNDL1qgtHHjfEOUelb/S+Cgzf4Emj2376AEr6foiW+6s125rjXEtGul/qM1kgCzJgMHZC7PxKAbUb7mmiifoGpU+0HxoiWBDSntWcdqQFZ2+Sg4hdT2PAhf4mlJmZiop0nxom8C3opdNIkcyIIQcg7cse49f3d3AjmDmkoGteKPmnpuB+xmoxvVsYkMHrqAvMJwXhC+sKIYCD/d5khLXhlWMkuKZr43UyKGnrM2KI6dSVty+2iWStHGZvf2eRZ5KgQ2990iObgtC4uMtPjkyNaRyaDZfC3kOlS+OjIxkmtqWqJtnLaUwxMRCAdPdOHxKMdPRoLrh66zpmey2idJnYudIF+nR2FAwPiHRfbkJPFxFsaQcM6YsB0H7ULZIzQFlaZ3+z5Tq9jPUGz3xNaD4O3R2yQoOw9zj4psqp8ZYDWK44ej3MDleG3G0rt8o=
  on:
    tags: true
    repo: scrapinghub/scrapy-poet
    condition: "$TOXENV == py38"
  distributions: sdist bdist_wheel
